### ISSUE TITLE
Invalid input syntax for type integer: "components"

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-sprig#192]
When posting using Sprig I am getting an error
`Next yii\db\Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "components"`

when I do a normal form post (without Sprig) I cannot get replicate the error.

I am not sure it is a Sprig issue but I am guessing based on error happening when using Sprig and due to "field" named "components".

### Versions
- Plugin version: 1.10.4
- Craft version: 3.7.26
- PostgreSQL 13

**Comment by bencroker** [comment]
Can you please provide a full stack trace to help find the source of the error?

**Comment by philipboomy** [comment]
Of course.

```
2021-12-23 09:03:16 [-][62][tj9ejmh4l7kfkldti1pap6fktp][error][yii\db\Exception] PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "components" in /Users/pat/Sites/wonderdays/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT "element...')
#2 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/db/Command.php(424): yii\db\Command->queryInternal('fetch', NULL)
#3 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne()
#4 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/db/Query.php(167): yii\db\Query->one(NULL)
#5 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1634): craft\db\Query->one(NULL)
#6 /Users/philip/Sites/devwebsite/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\elements\db\ElementQuery->one()
#7 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\UserQuery), 'one', Array, 'method', false, false)
#8 /Users/philip/Sites/devwebsite/storage/runtime/compiled_templates/df/df980f46a418ec17ff50c398019dcf8a9845a291339bbf14ecfab75e1341df20.php(82): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\UserQuery), 'one', Array, 'method')
#9 /Users/philip/Sites/devwebsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_956993f24693f13d68fce58af496d75e71b88a5fa9399ee287e47df66ecc1949->doDisplay(Array, Array)
#10 /Users/philip/Sites/devwebsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/philip/Sites/devwebsite/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#12 /Users/philip/Sites/devwebsite/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /Users/philip/Sites/devwebsite/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_components/sup...', Array)
#15 /Users/philip/Sites/devwebsite/vendor/putyourlightson/craft-sprig-core/src/controllers/ComponentsController.php(64): craft\web\View->renderTemplate('_components/sup...', '[<span class="s...')
#16 [internal function]: putyourlightson\sprig\controllers\ComponentsController->actionRender()
#17 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#19 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('render', Array)
#20 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('sprig-core/comp...', Array)
#21 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('sprig-core/comp...', Array)
#22 /Users/philip/Sites/devwebsite/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /Users/philip/Sites/devwebsite/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /Users/philip/Sites/devwebsite/web/index.php(21): yii\base\Application->run()
#25 /Users/philip/.composer/vendor/laravel/valet/server.php(235): require('/Users/philip/Site...')
#26 {main}
```

PS If it is something with Sprig then ping me and I will provide as much data/help as I can.

**Comment by bencroker** [comment]
Thanks. What is the `components` field exactly, and how are you accessing it here?

**Comment by philipboomy** [comment]
Thats the thing. I don't know what that field is. All can I find is a "component" field in "sprig_playgrounds" but not "components" - I refactored some code and now I am getting this error. Didn't update Sprig or Craft. I am leaning towards something I have done but can't understand why I can replicate it with a non-sprig post.

**Comment by bencroker** [comment]
My guess would be a typo in your template. From the stack trace, it looks like the error is originating from a `UserQuery`.

**Comment by philipboomy** [comment]
Thank you for pointer! I will dig deeper. Will close this issue when confirmed user error (occam razor)

**Comment by philipboomy** [comment]
Thanks for your guidance. Helped me find the issue. In my controller I was getting url segment using craft app request which does not work with the ajax that Sprig does. User error of course.
