### ISSUE TITLE
Contact Form Recipe - status 500

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-sprig#218]
### Question
I'm attempting to use the [Contact Form recipe](https://putyourlightson.com/sprig/cookbook#contact-form) and it is sort of working. I receive emails but the page doesn't refresh with sprig and I see a 500 error in the fetch/xhr tab of developer tools.

![image](https://user-images.githubusercontent.com/6899490/164255220-43204aab-7f1f-4ae4-90ef-91315e6ebfe7.png)

Sprig is working elsewhere on the site with pagination and search filtering.

All testing is done locally and have sendgrid set up to send messages.

--
Receiving messages, but success message is that no message was sent and also XHR 500 error.
-- 

Please advise

Main template:

```
{# contact form #}
{{ sprig('_components/contact-form') }}
```
_components/contact-form template

```
  <section class="py-12 bg-green-100">
    <div class="container">
      <div class="w-full prose prose-lg">

        {% macro errorList(errors) %}
            {% if errors %}
                {{ ul(errors, {class: 'errors text-red-500'}) }}
            {% endif %}
        {% endmacro %}

        {# Sets default values if not defined by the input fields below #}
        {% set fromName = fromName ?? '' %}
        {% set fromEmail = fromEmail ?? '' %}
        {% set subject = subject ?? '' %}
        {% set message = message ?? '' %}

        {# The `success` variable is defined by the contact form controller on success #}
        <div class="w-1/2 p-12 mx-auto text-white bg-red-500">
          {% if success is defined and success %}

          <p>{{ fromName }}, Your message was successfully sent!</p>

          {% else %}
            <p>
              no success
            </p>
          {% endif %}
        </div><!-- /.testing -->


        <form
          method="post"
          sprig s-method="post"
          s-action="contact-form/send"
          accept-charset="UTF-8"
          class="flex flex-col gap-8 mx-auto lg:w-1/2">
            {{ csrfInput() }}
            {# {{ actionInput('contact-form/send') }} #}
            {# {{ redirectInput('contact/thanks') }} #}


            <h2 class="mb-0">Contact Us</h2>

            <div class="relative">
              {{ input('text', 'fromName', message.fromName ?? '', {
                  id: 'from-name',
                  autocomplete: 'name',
                  class: 'floating-input w-full',
                  'aria-label': "Your Name"|t,
                  placeholder: "Your Name"|t,

              }) }}
              <label for="from-name" class="floating-label">{{ "Full Name"|t }}</label>
              {{ message ? _self.errorList(message.getErrors('fromName')) }}
            </div>

            <div class="relative">
              {{ input('email', 'fromEmail', message.fromEmail ?? '', {
                id: 'from-email',
                autocomplete: 'email',
                class: 'floating-input w-full',
                'aria-label': "Email"|t,
                placeholder: "Email"|t,
              }) }}
              <label for="from-email" class="floating-label">{{ "Email"|t }}</label>
              {{ message ? _self.errorList(message.getErrors('fromEmail')) }}
            </div><!-- /.relative -->

            <div class="relative">
              {{ input('text', 'subject', message.subject ?? '', {
                  id: 'subject',
                  class: 'floating-input w-full',
                  'aria-label': "Submect"|t,
                  placeholder: "Subject"|t,
              }) }}
              <label for="subject" class="floating-label">{{ "Subject"|t }}</label>
              {{ message ? _self.errorList(message.getErrors('subject')) }}
            </div><!-- /.relative -->

            <div class="relative">
              {{ tag('textarea', {
                  text: message.message ?? '',
                  id: 'message',
                  name: 'message',
                  rows: 10,
                  cols: 40,
                  class: 'floating-input w-full',
                  'aria-label': "Message"|t,
                  placeholder: "Message"|t,
              }) }}
              <label for="message" class="floating-label">{{ "Message"|t }}</label>
              {{ message ? _self.errorList(message.getErrors('message')) }}
            </div><!-- /.relative -->

            <button type="submit" class="self-start btn">Send</button>
        </form>

      </div><!-- /.prose -->
    </div><!-- /.container -->
  </section>
```

On line 20-28 there is a testing div that outputs success or not and it always outputs no success even if I recieve the message sent.
### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
Can you track down the error in the logs? An exception is likely being thrown, which will be logged with a stack trace that should tell you more.

**Comment by CreateSean** [comment]
Ben, 

I looked but haven't found anything that stands out to me. I can see the $_POST content:

```
$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'fromName' => 'Sean'
    'fromEmail' => 'none@domain.com'
    'subject' => 'form test'
    'message' => 'testing the form'
    'sprig:siteId' => '84a19c9f9f6a115eccbf8e96810609d4cc5cd30a25b9955f201b07affc9e74ee2'
    'sprig:template' => '2de0b0c1a15e3c4557b43e34fc1eaceab59bfc01ac7a42e103d8785307ce9f20_components/contact-form'
]
```

and then a search for `error` and here is what I found:

```
2022-04-20 13:07:45 [-][1][f9aba9a67c0d6e535b4472180d052663][error][Twig\Error\RuntimeError] Twig\Error\RuntimeError: Impossible to invoke a method ("getErrors") on a string variable ("testing the form"). in /var/www/html/templates/_components/contact-form.twig:55
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), 'testing the for...', 'getErrors', Array, 'method', false, false)
#1 /var/www/html/storage/runtime/compiled_templates/d7/d788cc4fa2448c7d34fc6b1a238939b0b95dddbdee564263ac8caff99087c002.php(120): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), 'testing the for...', 'getErrors', Array, 'method')
#2 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8e27417c797a3fb9261aae45d9b8db7edef80c6814b415a301e49c4521dd74b3->doDisplay(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
```

there' smore but I think this is the relevant bit. `contact-form.twig:55` 

lines 44-55 of that file:

```
            <div class="relative">
              {{ input('text', 'fromName', message.fromName ?? '', {
                  id: 'from-name',
                  autocomplete: 'name',
                  class: 'floating-input w-full',
                  'aria-label': "Your Name"|t,
                  placeholder: "Your Name"|t,

              }) }}
              <label for="from-name" class="floating-label">{{ "Full Name"|t }}</label>
              {{ message ? _self.errorList(message.getErrors('fromName')) }}
            </div>
```

in case it helps - have put the full log here: https://www.dropbox.com/s/dkqugkx2882q6mc/error-log.zip?dl=0

**Comment by bencroker** [comment]
The error is clearly saying that it is `Impossible to invoke a method ("getErrors") on a string variable ("testing the form")`.

It's telling you that `message` is a string, so you can't call `message.getErrors('fromName')`.

**Comment by CreateSean** [comment]
Ben,

Sorry - not sure why I didn't see/understand that. But yes now I'm good. Thank you for your time.
